# Part 1

The file "Purchase_Data.csv" contains purchase data at a Chinese supermarket for various products.  Read this csv into a dataframe called df_data and use the head() method to check that you have read in the data correctly. Make sure you import pandas.

In [4]:
#Write your code here
import pandas as pd
df_data = pd.read_csv("Data/Purchase_Data.csv")
df_data.head()

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
2,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
3,2.020000e+11,7/15/15 12:16,G816,7070891,70401,1.0,6.0
4,2.020000e+11,7/15/15 12:16,G816,7090363,70401,1.0,6.0

Use the dtypes attribute to view how each column is stored

In [6]:
#Write your code here
df_data.dtypes

invoice_number    float64
invoice_time          str
store_id              str
product_id          int64
category_id         int64
num_item          float64
price             float64
dtype: object

Slice the first two columns using .loc and store the result in a variable called result_1.

In [16]:
#Write you code here
result_1 = df_data.loc[:,:"invoice_time"]  # asked gemini to remind  me how to use it.
result_1

      invoice_number   invoice_time
0       2.020000e+11  7/15/15 10:45
1       2.020000e+11  7/15/15 12:16
2       2.020000e+11  7/15/15 12:16
3       2.020000e+11  7/15/15 12:16
4       2.020000e+11  7/15/15 12:16
...              ...            ...
5377    2.020000e+11   9/5/15 23:07
5378    2.020000e+11   9/5/15 23:23
5379    2.020000e+11   9/5/15 23:24
5380    2.020000e+11   9/5/15 23:32
5381    2.020000e+11   9/5/15 23:38

[5382 rows x 2 columns]

Slice the first two rows using .loc and store the result in a variable called result_2.

In [19]:
#Write you code here
result_2 = df_data.loc[:1]
result_2

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0

Slice the first four rows and the first five columns and store the result in a variable called result_3.

In [22]:
#Write your code here
result_3 = df_data.loc[:3, :"category_id"]
result_3

   invoice_number   invoice_time store_id  product_id  category_id
0    2.020000e+11  7/15/15 10:45     G816     7000300       210101
1    2.020000e+11  7/15/15 12:16     G816     7070884        70203
2    2.020000e+11  7/15/15 12:16     G816     7070884        70203
3    2.020000e+11  7/15/15 12:16     G816     7070891        70401

Slice rows 0,4,6 and columns invoice time and price and store the result in variable called result_4.

In [24]:
#Write your code here
result_4 = df_data.loc[[0,4,6],["invoice_time","price"]]
result_4

    invoice_time  price
0  7/15/15 10:45    2.0
4  7/15/15 12:16    6.0
6  7/15/15 15:28    2.0

Store the number rows in a variable called num_rows.

In [28]:
num_rows = df_data.shape[0]
num_rows

5382

Print out the last row of the data to dataframe. **Hint:** use the variable num_rows from the previous exercise.

In [38]:
#Write your code here
df_data.loc[[num_rows-1]]  # Asked gemini because i forgot about having to use 2 square brackets

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
5381,2.020000e+11,9/5/15 23:38,G619,23030206,210101,1.0,2.0

# Part 2

Compute the average and max price charged.  Store the results in variables called avg_price and max_price

In [46]:
#Write your code here
avg_price = float(df_data.loc[:,"price"].mean())
max_price = float(df_data.loc[:,"price"].max())
print(avg_price)
print(max_price)

3.1920522110741363
6.01

Compute the average price and average number of items purchased with only a single call to the mean() method. Store these averages in avg_price and avg_num_items.

In [49]:
#Write you code here
avg_price, avg_num_items = df_data.loc[:, ["price", "num_item"]].mean()
print(avg_price)
print(avg_num_items)

3.1920522110741363
1.2983091787439613

Create a column called "total", which is the product of the price and num_item columns.

In [85]:
#Write your code here
df_data["total"] = df_data["price"] * df_data["num_item"]
df_data

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price,total
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0,2.0
2,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0,2.0
3,2.020000e+11,7/15/15 12:16,G816,7070891,70401,1.0,6.0,6.0
4,2.020000e+11,7/15/15 12:16,G816,7090363,70401,1.0,6.0,6.0
...,...,...,...,...,...,...,...,...
5377,2.020000e+11,9/5/15 23:07,300,7308017,210101,1.0,3.0,3.0
5378,2.020000e+11,9/5/15 23:23,G619,7070891,70401,1.0,6.0,6.0
5379,2.020000e+11,9/5/15 23:24,G619,7071096,70201,1.0,5.0,5.0
5380,2.020000e+11,9/5/15 23:32,G619,15000231,70301,2.0,2.0,4.0
5381,2.020000e+11,9/5/15 23:38,G619,23030206,210101,1.0,2.0,2.0

What is the avgerage price of the three most expensive purchases?

In [55]:
#Write your code here
df_sorted = df_data.sort_values(by="total", ascending=False)
avg_top_3_purchase = df_sorted.iloc[:3]["total"].mean() # used gemini to check if i was correct 
avg_top_3_purchase

np.float64(164.0)

How many different products are there?

In [60]:
#Write your code here
num_product = len(df_data[:]["product_id"].unique())
num_product

53

Find the difference between the mean and median of the column total.  Use the describe() method and then index the dataframe it returns.

In [78]:
#Write your code here
total_mean = df_data.describe().loc["mean", "total"]
total_median = df_data.describe().loc["50%", "total"]
diff = total_mean - total_median
diff

np.float64(0.9318078781127839)

Use the drop() method to delete the column total from the dataframe df_data.

In [86]:
#Write your code here
df_data = df_data.drop(columns=["total"]) # asked gemini
df_data.head()

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
2,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
3,2.020000e+11,7/15/15 12:16,G816,7070891,70401,1.0,6.0
4,2.020000e+11,7/15/15 12:16,G816,7090363,70401,1.0,6.0

Let's dig a little deeper into the data set and answer some basic question.

In [1]:
#Write your code here

First, covert the column invoice time to a datetime column. Print out the new column types to make sure this was done correctly

In [88]:
#Write your code here

df_data["invoice_time"].to_timestamp
df_data.dtypes

invoice_number    float64
invoice_time          str
store_id              str
product_id          int64
category_id         int64
num_item          float64
price             float64
dtype: object

Next, let's create columns called "DOW" and "Month", which store the corresponding weekday and month of the invoice respectively.  Print the head of the dataframe to make sure this was done correctly.

In [2]:
#Write your code here

Create a variable called num_purchases_wed, which stores the number of purchases made on Wednesday?  You should use value_counts and then index the series it return.

In [3]:
#Write your code here

# Part 3

In this set of practice exercises, we will be working with a demographic data regarding the passengers aboard the Titanic.  Read in the data frame and use the head() method to check that it was read in correctly.

In [4]:
#Write your code here

Use the rename method to change the column "Name" to "Passenger_Name" and the column "Ticket" to "Ticket_Num".

In [5]:
#Write your code here

Change the index of the df_titanic to the column PasengerID.

In [6]:
#Write your code here

Select the name of passenger 896

In [7]:
#Write your code here

Change the index back to row numbers but making sure that we don't lose the PassengerId column.

In [8]:
#Write your code here

How many missing entries are there in the Age column? Use the isnull() method and recall than Booleans are exactly like 1s (True) and 0s (False).

In [9]:
#Write you code here

Compute the avg age of passengers ignoring the missing data.

In [10]:
#Write your code here

Using the fillna() method replace the missing values in the Age column with the mean.

In [11]:
#Write your code here

What is the average age of the 5 oldest passengers? The reset_index method will be helpful here.

In [12]:
#Write your code here